parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Beyerz\:
        resource: '../*'
        exclude: '../{Tests}'

    Beyerz\OpenGraphProtocolBundle\Libraries\OpenGraph:
        # redundant thanks to _defaults, but value is overridable on each service
        autowire: true
        # not required, will help in our example
        public: true

    Beyerz\OpenGraphProtocolBundle\Twig\Extensions\OpenGraphProtocolExtension:
        autowire: true
        public: true
